# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build ffkb'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["fingerpunch/ffkb/byomcu/v2"]'
      layout: '["manna-harbour_miryoku"]'
