name: Build QMK firmware
on:
  push:
    branches:
      - main
      - master
      - 'develop**'
      - github-actions-build
jobs:

  Build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
    steps:
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build firmware
      shell: bash
      run: |
        wget -q https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O jq
        chmod +x jq
        mv jq /usr/local/sbin/

        make_command="bin/fp_build.sh -k ffkb/byomcu/v3 -m manna-harbour_miryoku -e MIRYOKU_ALPHAS=QWERTY -r"
        echo "${make_command}"
        $make_command

    - name: Debug - List files
      run: ls -al

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: qmk_fingerpunch_${{ github.actor }}
        path: |
          *.hex
          *.bin
          *.uf2
